### ISSUE TITLE
The zip file built from the source code could not be found in the path mentioned in the documentation

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-distribution#1007]
https://github.com/ballerina-platform/ballerina-distribution#building-the-source

The path mentioned in the above link for zip file which contains the built source code cannot be found

I think it should be corrected to the following path name

/ballerina/build/distributions/ballerina-<version>-SNAPSHOT.zip

**Comment by ruvi-d** [comment]
A brief description of the various output artifacts would be nice to have. I got 5 artifacts in my distributions folder. There are 3 OS specific packages which are self explanatory, but the purpose of the other two is not clear. e.g.
```
ballerina-distribution/ballerina/build/distributions
├── ballerina-linux-swan-lake-preview8-SNAPSHOT.zip
├── ballerina-macos-swan-lake-preview8-SNAPSHOT.zip
├── ballerina-slp7.zip
├── ballerina-swan-lake-preview8-SNAPSHOT.zip
└── ballerina-windows-swan-lake-preview8-SNAPSHOT.zip
```
