### ISSUE TITLE
Disabled tests with service type migrations

### ISSUE THREAD

**Issue by niveathika** [ballerina-platform/ballerina-distribution#1056]
**Description:**

BBE Validation
 
- [x] websub-service-integration-sample
- [x] websub-internal-hub-sample
- [x] websocket-cookie
- [x] websocket-retry
- [x] websocket-failover
- [x] websocket-chat-application
- [x] websocket-proxy-server
- [x] http-to-websocket-upgrade
- [x] websocket-basic-sample
- [x] websocket-client
- [ ] http-filters

https://github.com/ballerina-platform/ballerina-distribution/pull/1055/commits/bc50e77de186e4bb1451276f95aad2a4ebaec6e8

**Comment by niveathika** [comment]
Websub bbe enabled with https://github.com/ballerina-platform/ballerina-distribution/pull/1059

**Comment by niveathika** [comment]
@chamil321 @Bhashinee Can we close this?

**Comment by Bhashinee** [comment]
WebSocket ones are done. Not sure about the HTTP filters.

**Comment by chamil321** [comment]
HTTP filters are no longer available. We can remove the entry from this issue and close it. We can enable it later whenever this feature is added.

**Comment by niveathika** [comment]
Ack
