### ISSUE TITLE
BALLERINA_HOME set for v0.983.0-1 on linux/rpm is wrong

### ISSUE THREAD

**Issue by abhishekkr** [ballerina-platform/ballerina-distribution#112]
**Description:**
I've installed from ballerina.io provided RPM `v0.983.0-1.x86-64`.  It sets `BALLERINA_HOME=/usr/lib64/ballerina/ballerina-0.983.0`, but the actual value as per dir structure created need to be `/usr/lib64/ballerina/ballerina-platform-0.983.0`.
This in turn results into wrong error message as well, which is `Error: JAVA_HOME is not defined correctly.`.

**Affected Product Version:**
* found it for `v0.983.0-1.x86_64`

**OS, DB, other environment details and versions:**    
* Fedora (GNU/Linux)

**Steps to reproduce:**
* Just install this version ballerina rpm on any linux and try use it.

I've fixed it locally and will submit a patch.

**Comment by abhishekkr** [comment]
PR at https://github.com/ballerina-platform/ballerina-distribution/pull/113

**Comment by keizer619** [comment]
Thank you reporting and doing a fix. We have already created an issue [1] in ballerina-lang repository. This has happened due to a bug in rpm generation script spec file. 

[1] https://github.com/ballerina-platform/ballerina-lang/issues/11496

**Comment by abhishekkr** [comment]
@keizer619 oh cool, didn't see that

although, this patch will make the script robust to handle any further similar issues

**Comment by keizer619** [comment]
I am closing this issue as its been already reported and fixed ballerina-platform/ballerina-lang#11496. 

@abhishekkr
Regarding the patch, please refer the comment i have added for https://github.com/ballerina-platform/ballerina-distribution/pull/113
