### ISSUE TITLE
Replace the balleina/lang.float import in the modules BBE

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-distribution#1247]
**Description:**
$title, introduced in https://github.com/ballerina-platform/ballerina-distribution/pull/1246 as a replacement for the `ballerina/math` import.

But it's not the best example, since there's a predeclared import for lang.float. Need to find a suitable alternative with a constant.

**Comment by praneesha** [comment]
Closing since this BBE is removed by the revamp done for Swan Lake Beta1.
