### ISSUE TITLE
Pack zip file sizes have inceased

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-distribution#1290]
**Description:**
Current zip file without JRE (ballerina-swan-lake-alpha2-SNAPSHOT.zip) size is around 229.4MB
Zip files with JRE (ballerina-windows-swan-lake-alpha2-SNAPSHOT.zip) is around 374.5MB

How ever i noticed Final installers sizes are quite small where as ballerina-windows-installer-x64-swan-lake-alpha1.msi is around 155MB. Seems like this could be an issue with Gradle task of zipping files

**Comment by suhand** [comment]
![image](https://user-images.githubusercontent.com/5634722/112100933-df8b4380-8bcb-11eb-83ce-1e3ca160bf59.png)

![image](https://user-images.githubusercontent.com/5634722/112101097-1f522b00-8bcc-11eb-8483-58e468a9513c.png)

**Comment by udda1996** [comment]
Fix dist zipping issue #1924
