### ISSUE TITLE
Incorrect info in INSTALL.txt

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-distribution#1346]
See https://github.com/ballerina-platform/ballerina-distribution/blob/19a270a8b594c168f59874c24938c6eddf52a2fa/resources/tools/INSTALL.txt#L27

The JDK directory path contains the name of a JDK 8 version. Shouldn't this be updated to a JDK 11 path?

Also We don't publish the SL plugin to the marketplace.
https://github.com/ballerina-platform/ballerina-distribution/blob/19a270a8b594c168f59874c24938c6eddf52a2fa/resources/tools/INSTALL.txt#L50

**Comment by keizer619** [comment]
Now VSCode swan lake releases have been published
