### ISSUE TITLE
Enable MySQL and JDBC complex BBEs after time migrarion

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-distribution#1385]
**Description:**
Need to enable the following BBEs which disabled in here(https://github.com/ballerina-platform/ballerina-distribution/commit/9c0b5fafd02bdca0117d7dc83a7f04d8d709c0db) due to time API changes.
- mysql-complex-type-queries
- jdbc-complex-type-queries

**Comment by niveathika** [comment]
@BuddhiWathsala Do we need any update on the bbe? These are permanently removed from build since JDBC & MySQL packages are removed from dist

**Comment by praneesha** [comment]
These BBEs are revamped and added in [1] and [2] now.

[1] https://ballerina.io/learn/by-example/mysql-complex-type-queries
[2] https://ballerina.io/learn/by-example/jdbc-complex-type-queries
