### ISSUE TITLE
Add an example how to get text value of an XML element to BBE

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-distribution#1597]
**Description:**
$Subject

We have 

```
    xml bookXML = xml `<book>
                <name>Sherlock Holmes</name>
                <author>
                    <fname title="Sir">Arthur</fname>
                    <mname>Conan</mname>
                    <lname>Doyle</lname>
                </author>
                <bar:year xmlns:bar="http://ballerina.com/a">2019</bar:year>
                <!--Price: $10-->
                </book>`;
```

how to get the text value of <book>/<name>?
the result need to return `Sherlock Homes`

Solution: 

Use `bookXml/<name>/*`

**Comment by abeykoon** [comment]
Basically, /* returns  sub elements or if it is a leaf element, value of the element

**Comment by lasinicl** [comment]
With the new BBE structure(since slbeta1), we have [XML Navigation](https://ballerina.io/learn/by-example/xml-navigation). Hence closing this issue.
