### ISSUE TITLE
Invalid Syntax for  Basic Publisher and Subscriber BBE

### ISSUE THREAD

**Issue by sanjana** [ballerina-platform/ballerina-distribution#1602]
**Description:**
The BBE of [Basic Publisher and Subscriber](https://ballerina.io/learn/by-example/nats-basic-client.html) has a syntax error and is not been updated with the SLA4 compatible syntax changes #1472. 

The code sample currently published on the [ballerina.io](https://ballerina.io/learn/by-example/nats-basic-client.html) website.
![image](https://user-images.githubusercontent.com/9464997/115524594-f0eb6c80-a2ab-11eb-888f-b5cd8829a5e4.png)

When the above code sample is copied to VS code, the following error is produced.
![image](https://user-images.githubusercontent.com/9464997/115523105-58082180-a2aa-11eb-969a-0d29c55194bf.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by praneesha** [comment]
This is resolved now in https://ballerina.io/learn/by-example/nats-basic-pub-sub.
