### ISSUE TITLE
Ballerina command does not work when `JAVA_HOME` is not defined

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-distribution#177]
**Description:**
Seems like the router script does not pick the packed jre version properly after https://github.com/ballerina-platform/ballerina-distribution/pull/170.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
1.0.0-beta

**OS, DB, other environment details and versions:**    
OS Version: Ubuntu 18.04

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
This is reported at ballerina repository as well, lets keep that issue and close this
https://github.com/ballerina-platform/ballerina-lang/issues/18457
