### ISSUE TITLE
Run text comments have not removed from stdlib BBEs

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#1878]
**Description:**
We need to do $subject to be in consistent.

ex: 
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/16300038/120418471-39537b00-c37e-11eb-9817-219c22605d1e.png">

https://dev.ballerina.io/learn/by-example/url-encode-decode.html

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by ldclakmal** [comment]
This may be a caching issue. Both dev and prod links works fine for me.
https://dev.ballerina.io/learn/by-example/url-encode-decode.html
https://ballerina.io/learn/by-example/url-encode-decode
![image](https://user-images.githubusercontent.com/9639050/120584332-6d49a180-c44d-11eb-8cf8-21ba52402aee.png)

**Comment by anupama-pathirage** [comment]
@ldclakmal Created this issue before you all remove these texts yesterday. So the purpose of this issue was to start that work. :) Seems it is done now. If we have updated all the stdlib BBEs with run text removal, we can close this issue.

**Comment by ldclakmal** [comment]
Ah got it :) I did a quick search for the common phrase ("To run this sample...") we were using in `.out` files throughout all the BBEs (`examples` directory of ballerina-distribution repo). Seems like all the stdlib BBEs are okay. Here is the search results:

![image](https://user-images.githubusercontent.com/9639050/120585107-c960f580-c44e-11eb-90bd-00be30810575.png)

**Comment by ldclakmal** [comment]
Closing the issue with above comment. https://github.com/ballerina-platform/ballerina-distribution/issues/1878#issuecomment-853545702
