### ISSUE TITLE
Supporting AdoptOpenJDK native builds for ARM based Mac with Ballerina distribution

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#1936]
**Description:**
Currently AdoptOpenJDK is in the process to provide native builds to support ARM based Mac architecture. Once it is available, we can try to use that with Ballerina distribution.

We also need to evaluate how we can ship a separate Ballerina distribution that is compatible with the new ARM architecture.

**Related Issues (optional):**
https://github.com/AdoptOpenJDK/openjdk-build/issues/1922

**Comment by keizer619** [comment]
We now have an ARM base mac installer. Hence I will be closing this issue
