### ISSUE TITLE
Link API referencefrom BBE

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-distribution#1952]
**Description:**
It'll be very useful if BBE had `More information` section with relevant links 

eg:

https://ballerina.io/learn/by-example/arrays.html
should link to 
https://docs.central.ballerina.io/ballerina/lang.array/latest

**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by anupama-pathirage** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-distribution/issues/1951 Hence closing
