### ISSUE TITLE
Need to remove the warning from the WebSocket listener BBE

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-distribution#1992]
**Description:**
$Subject.

Vscode shows the following warning.  I think it better to keep BBEs without warning. Therefore we can remove this warning by changing the service class to `isolated`

<img width="842" alt="Screenshot 2021-06-21 at 2 25 52 PM" src="https://user-images.githubusercontent.com/12771261/122736346-8fd91880-d29d-11eb-8f6f-4fc500488cb0.png">

Affected Versions:
SLBeta1

**Comment by Bhashinee** [comment]
Ideally, users don't have to mark services as isolated as the compiler infers the isolated state. This warning comes because this is not yet supported by the compiler. So once that is fixed, this warning will not get printed anymore and the decision was taken not to mark them as isolated now.
