### ISSUE TITLE
Removing redundant `example` word  from database BBE descriptions

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [ballerina-platform/ballerina-distribution#2022]
**Description:**
There is no need to use the word example again as these are under the `BBE`. 

<img width="348" alt="Screenshot 2021-06-28 at 11 33 27 AM" src="https://user-images.githubusercontent.com/12771261/123587969-b26eb280-d804-11eb-8e7e-3d0535158b63.png">

**Comment by kalaiyarasiganeshalingam** [comment]
@lahirusamith

**Comment by lahirusamith** [comment]
Will correct that thanks!
