### ISSUE TITLE
Incorrect wording in "strands" playground example.

### ISSUE THREAD

**Issue by kasabov** [ballerina-platform/ballerina-distribution#2090]
**Description:**
Incorrect wording in "strands" playground example. Word "been" should be replaced with "between" in two instances.

**Steps to reproduce:**
Go to https://ballerina.io/learn/by-example/strands

**Affected Versions:**
latest master branch

**OS, DB, other environment details and versions:**
web

**Comment by keizer619** [comment]
Closing as this have been merged https://github.com/ballerina-platform/ballerina-distribution/pull/2091
