### ISSUE TITLE
I am getting this on compile : Error: Ballerina is supported only on JDK 1.8

### ISSUE THREAD

**Issue by rangapv** [ballerina-platform/ballerina-distribution#2211]
**Description:**

I am getting this on compile : 
Error: Ballerina is supported only on JDK 1.8
**Steps to reproduce:**
When I try to compile any simple programs I an getting the error....
**Affected Versions:**

**OS, DB, other environment details and versions:**
OS: Ubuntu 18.04
$ java --version
java 17 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by rangapv** [comment]
Does the java 17 version an issue ?

**Comment by keizer619** [comment]
Whats the Ballerina version you are using?
Latest Ballerina swan lake beta 3 version supports only Java 11
Ballerina 1.2.19 version supports only Java 1.8

Ballerina does not support Java 17. However if you have installed Ballerina via an installer, it will include supported JRE inbuilt. So even you are system has Java 17, Ballerina should work

**Comment by keizer619** [comment]
@rangapv Are you using ballerina zip? If so then you can use installer as i mentioned un above comment. Please feel free to reopen the issue if required
