### ISSUE TITLE
Ballerina command version points to 1.1.0-alpha

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#234]
**Description:**
After installing the 1.1.0-alpha on Mac, when we check the ballerina version command, below is the output.

```
$ ballerina -v
jBallerina 1.1.0-alpha
Language specification 2019R3
Command 1.1.0-alpha
```

Command version should be 0.8.0 as discussed.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
This has been fixed by restructuring the ballerina-command module. Otherwise it will be automatically bumped to the parent version (in this case 1.1.0-alpha) by the maven release plugin
