### ISSUE TITLE
Output verification fails due to the removal of Listener logs

### ISSUE THREAD

**Issue by chamil321** [ballerina-platform/ballerina-distribution#2343]
**Description:**
As a result of https://github.com/ballerina-platform/ballerina-standard-library/issues/2040, the output verification logic fails. 
https://github.com/ballerina-platform/ballerina-distribution/blob/master/ballerina/build.gradle#L743

**Comment by daneshk** [comment]
This issue occurs because we intentionally remove the log print when a listener starts. Therefore, there is nothing to verify in the listener output. Hence, the issue is closed.
