### ISSUE TITLE
Help for ballerina update command is missing

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#237]
**Description:**
This is on 1.1.0-alpha

```
$ballerina help update
ballerina: unknown help topic `update`
Run 'ballerina help' for usage.
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Fixed 
https://github.com/ballerina-platform/ballerina-distribution/pull/292/commits/ab1c1145c76e86396e8187b03930759185392c9e
