### ISSUE TITLE
Ballerina command fails with "The system cannot find the path specified." error

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-distribution#239]
**Description:**
Run any ballerina command. 
```
ballerina.bat -v
The system cannot find the path specified.
Command 1.1.0-alpha
```

**Steps to reproduce:**
1) Installed ballerina 1.0.4 
2) Compile a program using ballerina 1.0.4
3) Install ballerina 1.1.0-alpha (pre-pack).
4) Run ballerina version. 

**Workaround**
- Delete the .ballerina folder in the home directory.

**Details**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763

**Comment by keizer619** [comment]
Fixed in following PR
https://github.com/ballerina-platform/ballerina-distribution/pull/293/commits/cfe7344e61542b0a91c9a893d9a5cc82a6977749
