### ISSUE TITLE
Revisit `ballerina help` output for consistency 

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#241]
**Description:**
On ballerina 1.1.0-alpha the `ballerina help` outputs the following.

```
$ ballerina help    
NAME
       The Ballerina build tool

SYNOPSIS
       ballerina [-v | --version] [-h | --help]
                 <command> [<args>]


DESCRIPTION
       Ballerina is a statically typed, concurrent programming language, focusing on network interaction and structured
       data. It is intended to be the core of a language-centric middleware platform. It has all the general-purpose
       functionality expected of a modern programming language, but it also has several unusual aspects that make it
       particularly suitable for its intended purpose.

       Find more information at: https://ballerina.io/


```

Questions
1. Is is correct to say "The Ballerina build tool"?
2. The text column width of "DESCRIPTION" is wider comparing with other commands "DESCRIPTION"

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Fixed in following commit
https://github.com/ballerina-platform/ballerina-distribution/pull/286/commits/867197c0a80956b2c8ce32b0c70511a328746050
