### ISSUE TITLE
Netty version needs to be updated

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-distribution#2412]
**Description:**
Currently Trivy scan is failing [1] and netty version has to be updated

- [x] TCP  @Bhashinee - https://github.com/ballerina-platform/module-ballerina-tcp/blob/22fec9aa1582ed31ae3a3dcfa23183cda4d18ef7/gradle.properties#L10
- [x] HTTP @chamil321  - https://github.com/ballerina-platform/module-ballerina-http/blob/2cf53524a467487dc7a005ea03c911f2f06423dc/gradle.properties#L7
- [x] Websocket @Bhashinee  - https://github.com/ballerina-platform/module-ballerina-websocket/blob/main/gradle.properties#L6

[1] https://github.com/ballerina-platform/ballerina-distribution/runs/4490096342?check_suite_focus=true#step:30:38

**Comment by ldclakmal** [comment]
Closing the issue since this is fixed.
