### ISSUE TITLE
`ballerina update` command does not direct user to next steps

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#243]
**Description:**
On ballerina 1.1.0-alpha, when you issue the `ballerina update`, it fails like the below.

```
$ ballerina update       
Current user does not have write permissions to directory
Using tool version: 0.8.1
```

What are the next steps of a user? 
User will be lost from this step on what to do next.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by hasithaa** [comment]
Same issue in Windows, But with different error message 

```
C:\Users\hasitha>ballerina update
Downloading ballerina-command-0.8.1
Cannot connect to the central server due toC:\Program Files\Ballerina\ballerina-command-tmp\ballerina-command-0.8.1.zip (The system cannot find the path specified)
Using tool version: 0.8.1
```

Issues

1) Not directing permission issues in windows. 
2) Need a space between error message and cause. `Cannot connect to the central server due to<ErrorMessage>`
