### ISSUE TITLE
Linux installer for 1.1.0-alpha doesn't work if the 1.0.5-SNAPSHOT installer was used

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-distribution#244]
**Description:**
$title.

**Comment by keizer619** [comment]
Now we are keeping installation in the same directory (usr/lib/ballerina)
Ubuntu does not allow to rewrite to same location so we need to unsinstall previous installation and install new one

> dpkg --remove ballerina-1.1.0-alpha
> dpkg -i ballerina-linux-installer-x64-1.1.0-beta.deb 

Or else we need to force install

> dpkg -i --force-overwrite ballerina-linux-installer-x64-1.1.0-alpha.deb
