### ISSUE TITLE
Ballerina update tool commands are not working

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-distribution#245]
**Description:**

`ballerina help` gives the following output:
```
   ...
   ...
   Update tool Commands:
        list       List available ballerina distributions
        fetch      Pull a given distribution version
        pull       Pull and use a given distribution version
        use        Switch to a specific distribution version
        update     Update to latest distribution version
        remove     Delete locally installed distribution version
```

When I run `ballerina list`, it says its an unknown command:
```
ballerina: unknown command 'list'
Run 'ballerina help' for usage.
```

**Comment by SupunS** [comment]
Seems there needs to be a `dist` keyword after the `ballerina` command.

i.e: `ballerina dist list`

**Comment by keizer619** [comment]
`dist` keyword is included in the main help and moved above sub commands into `help dist`

Fixed in following commit
https://github.com/ballerina-platform/ballerina-distribution/pull/286/commits/867197c0a80956b2c8ce32b0c70511a328746050
