### ISSUE TITLE
[dist use] No error when the given dist name is not available locally

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#249]
**Description:**

```
$ ballerina dist list               
Distributions available locally: 

  jballerina-1.1.0-alpha

Distributions available remotely: 

  jballerina-1.0.0
  jballerina-1.0.1
  jballerina-1.0.2
  jballerina-1.0.3
  jballerina-1.0.4

$ ballerina dist use jballerina-1.0.1

```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Fixed in following commit
https://github.com/ballerina-platform/ballerina-distribution/pull/276/commits/fe59e2a3fad76ed5b232156eec89da7223248a10
