### ISSUE TITLE
Inconsistent punctuation in `bal dist list` command

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#2496]
**Description:**

$subject .Refer below. New `bal dist list -a` is using backticks while we were using apostrophe earlier.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/16300038/150295058-6968d015-0e12-4fbd-8759-15537f29de2e.png">

**Affected Versions:**

SL GA RC1

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by hasithaa** [comment]
Also it is repeating ``` ... To list all the previous distributions execute `bal dist list -a` ``` multiple times.

**Comment by udda1996** [comment]
> Also it is repeating `` ... To list all the previous distributions execute `bal dist list -a` `` multiple times.

If each channel contains more than 10 distributions it shows `... To list all the previous distributions execute `bal dist list -a`. If a channel contains less than 10 distributions this line will not appear.

**Comment by udda1996** [comment]
Closing as this is fixed in https://github.com/ballerina-platform/ballerina-update-tool/pull/205
