### ISSUE TITLE
Wrong error when giving read and write permission to "/Library/Ballerina/distributions"

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#250]
**Description:**

```
sudo chmod 756 /Library/Ballerina/distributions
➜  ~ ballerina dist pull jballerina-1.0.4           
Cannot connect to the central server

```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by warunalakshitha** [comment]
This might be fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/284/
