### ISSUE TITLE
Mac installer time increases with number of distributions

### ISSUE THREAD

**Issue by KRVPerera** [ballerina-platform/ballerina-distribution#2511]
**Description:**

One of the reasons this happens is due to post [install script ](https://github.com/ballerina-platform/ballerina-distribution/blob/master/installers/mac/darwin/scripts/postinstall) with heavy `find` operations. There is no need to set permissions on existing distributions by the installer. Therefore we need to skip them.

Since the installer is touching unwanted files for the current installation this can be categorised as a bug.
I believe we solutions like below
## solution 1
```
cd __BALLERINA_VERSION__
find . -type d -exec chmod ugo+rx \{\} \;
find . -exec chmod ugo+r \{\} \;
```

## solution 2
We can also parallelise this stage into threads. 

We should also analyse if there are more reasons for the slowdown at this stage of the installer.

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KRVPerera** [comment]
Duplicate of #2537

**Comment by NipunaMadhushan** [comment]
Closing this issue since it was fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/2576
