### ISSUE TITLE
Invalid ballerina dist command does not give proper error message

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#253]
**Description:**
Try some invalid command like
`➜  ~ ballerina dist foo
`

The output is 
```
Unmatched argument at index 1: 'foo'
```

Instead, it should give some meaningful error like
```
ballerina: unknown command 'ballerina dist foo'
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Fixed
https://github.com/ballerina-platform/ballerina-distribution/pull/292/commits/cf22a64e722089a01eb0ee6b543a01eb54249d5f
