### ISSUE TITLE
The name given for the version of the `ballerina` command is not intuitive

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-distribution#255]
When you run `ballerina version`, you get the following:
```
$ ballerina version
jBallerina 1.1.0-alpha
Language specification 2019R3
Command 1.1.0-alpha
```
Instead of saying "Command", can we come up with a more descriptive name? I didn't realize "Command" meant the `ballerina` CLI command until Tharik pointed it out. Maybe simply refer to it as "`ballerina` command"?

**Comment by SupunS** [comment]
suggestion: `CLI version: x.x.x`

**Comment by Kishanthan** [comment]
We decided to use `Ballerina tool`

The expected output of `ballerina -v` is
```
$ ballerina [-v | version]
jBallerina: 1.1.0
Language specification: 2019R3
Ballerina tool: 0.8.0
```

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/386
