### ISSUE TITLE
 ballerina dist fetch -h gives the output as null - Description is missing

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#256]
**Description:**

<img width="222" alt="image" src="https://user-images.githubusercontent.com/16300038/70424375-506d2180-1a95-11ea-9bee-9a070769ef0f.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Fixed in following commit
https://github.com/ballerina-platform/ballerina-distribution/pull/276/commits/a7cd019a58077b654bd3e2da5c3ec986bae5de87
