### ISSUE TITLE
[Suggestion] Should `ballerina dist update` switch to the latest available distribution?

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-distribution#257]
**Description:**
Assume I have the following b7a versions and am using 1.0.4.

```cmd
$ ballerina dist list
Distributions available locally: 

  jballerina-1.1.0-alpha
* jballerina-1.0.4

Distributions available remotely: 

  jballerina-1.0.0
  jballerina-1.0.1
  jballerina-1.0.2
  jballerina-1.0.3
```

Should `ballerina dist update` switch to the latest version (jballerina-1.1.0-alpha) now? 

I assume if it was not available locally, we would pull the same anyway?

**Comment by keizer619** [comment]
Yes it will be bumped to the latest version. With the update tool we are not going to handle pre releases like beta and alpha. This why its not updated to above beta version. You can pull release 1.0.4 (which is latest in update server) then pull and switch into some release like 1.0.2. Then try to run ballerina dist update, it should update to 1.0.4.
