### ISSUE TITLE
The main help page contains the commands of the `ballerina dist` command

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-distribution#259]
The main help page you get when you run `ballerina help` contains the documentation for the commands of the `ballerina dist` command. Shouldn't these be documented in the help page you get when running `ballerina dist help`? 
![Screenshot from 2019-12-09 15-11-02](https://user-images.githubusercontent.com/6260009/70425027-64fde980-1a96-11ea-9afc-bbca827344ba.png)

**Comment by keizer619** [comment]
This is we need to think again. We might need to display these commands in the main help like 
"dist list" and "dist fetch" and repeat above list in the under "dist" command help

**Comment by pubudu91** [comment]
+1. But I was thinking more along the lines of just listing the `dist` command itself in the main help page.

**Comment by pubudu91** [comment]
Just checked how Git does this. They also seem to just list the immediate subcommands of `git` and if you need help on a particular subcommand, you run `git <subcommand> --help`.

**Comment by keizer619** [comment]
We have moved all these sub commands into "dist" and in the main command listing "dist" and "update" only. This is fixed in following commit
https://github.com/ballerina-platform/ballerina-distribution/pull/286/commits/867197c0a80956b2c8ce32b0c70511a328746050
