### ISSUE TITLE
ballerina dist update for invalid versions doesn't give any error

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#260]
**Description:**

<img width="255" alt="image" src="https://user-images.githubusercontent.com/16300038/70425127-9ecef000-1a96-11ea-8192-6fb8efbe89eb.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Duplicate issue
https://github.com/ballerina-platform/ballerina-distribution/issues/249

**Comment by keizer619** [comment]
Fixed in following commit
https://github.com/ballerina-platform/ballerina-distribution/pull/286/commits/76c9f87159da3c3f7465700b6fe5810065579b29
