### ISSUE TITLE
Inconsistent error messages when the update service is not found.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#262]
**Description:**

When the network is  disconnected, some commands says `Ballerina update service` is not available while some commands says `Central Server` not available. 

We need to have a consistent terminolgy to refer the remote update service.

<img width="328" alt="image" src="https://user-images.githubusercontent.com/16300038/70425390-2288dc80-1a97-11ea-9238-ba6bf333ebb1.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Fixed
https://github.com/ballerina-platform/ballerina-distribution/pull/292/commits/cf22a64e722089a01eb0ee6b543a01eb54249d5f
