### ISSUE TITLE
Inconsistent version info in 1.1.0-alpha and 1.0.x distributions

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-distribution#273]
When you run `ballerina version` on 1.1.0-alpha,
```
$ ballerina version
jBallerina 1.1.0-alpha
Language specification 2019R3
Command 1.1.0-alpha
```
And when you run it on 1.0.4,
```
$ ballerina version
Ballerina 1.0.4
Language specification 2019R3
Command 1.1.0-alpha
```
In the above it says `Ballerina 1.0.4` while in the former it says `jBallerina 1.1.0-alpha`. Wouldn't this be inconsistent, changing it to jBallerina all of a sudden?

**Comment by pubudu91** [comment]
Just realized, to fetch the 1.0.4 version, I used the command `ballerina dist fetch jballerina-1.0.4`. It's inconsistent there as well isn't it? In the CLI tool itself it refers to the 1.0.4 version as version `jballerina-1.0.4` while the output of the `ballerina version` command says `Ballerina 1.0.4`.

**Comment by keizer619** [comment]
From the 1.0.0 onwards it has to be jBallerina as we have introduced that. Unfortunately it has not updated in the those releasees (1.0.0 to 1.0.4). From 1.1.0 onwards we specifically mention it as jBallerina to be consistent with our references. For an instance when we run `ballerina dist pull jballerina-1.0.4`, we specify `jballerina` along with the version.
