### ISSUE TITLE
Distribution is unable to resolve gRPC BIR and JARs

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-distribution#2765]
**Description:**
When we update the stdlib versions in the distribution patch branch(`2201.0.x`), it gave us the following error.

```sh
> Task :ballerina:buildDistRepo
Building Distribution Repo ...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Bir missing for package :ballerina/grpc
Jar missing for package :ballerina/grpc
```

The gRPC BIR and JARs are correctly packed as usual. But this error arises unexpectedly in this branch.

**Steps to reproduce:**
Refer to this PR https://github.com/ballerina-platform/ballerina-distribution/pull/2757

**Comment by BuddhiWathsala** [comment]
Even this fix did not solve our issue https://github.com/ballerina-platform/ballerina-distribution/pull/2761

**Comment by udda1996** [comment]
Closing as this is fixed with Protobuf version update in gRPC.
