### ISSUE TITLE
`ballerina help dist update` prints help text for `ballerina update`

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-distribution#282]
**Description:**
$title. 

But output for `ballerina dist update -h` is correct.

**Affected Product Version:**
```cmd
$ ballerina -v
jBallerina 1.1.0-alpha
Language specification 2019R3
Command 1.1.0-alpha
```

**Comment by keizer619** [comment]
Fixed in following commit
https://github.com/ballerina-platform/ballerina-distribution/pull/286/commits/45cd120377451989a20484871182ba7635bc333a
