### ISSUE TITLE
awslambda module cannot be resolved

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-distribution#287]
**Description:**

The module `ballerinax/awslambda` cannot be resolved when used the pack fetched using the update tool. 
e.g: `ballerina build testMain.bal`

Same file works if I use a pack installed with the installer. 
e.g.: `/Library/Ballerina/ballerina-1.0.3/bin/ballerina build testMain.bal`

See bellow:

<img width="1680" alt="Screen Shot 2019-12-10 at 12 25 53 PM" src="https://user-images.githubusercontent.com/7834839/70503042-7bfd1400-1b48-11ea-91f9-3f119decda54.png">

Ballerina file:
```ballerina
import ballerinax/awslambda;

@awslambda:Function
public function foo(awslambda:Context ctx, json j) returns json|error {
    return j;
}
```

**Comment by keizer619** [comment]
This is fixed https://github.com/ballerina-platform/ballerina-distribution/pull/402/commits/14be0dfa399a23ef1df584153f16b053c6320cdf
