### ISSUE TITLE
`ballerina dist` related sub commands should have direction text for the users

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#291]
**Description:**
For example,
```
$ ballerina dist list       
Distributions available locally: 

  jballerina-1.1.0-alpha
  jballerina-1.0.2
  jballerina-1.0.4
* jballerina-1.0.3

Distributions available remotely: 

  jballerina-1.0.0
  jballerina-1.0.1
```
After issuing the above command, the user is not guided to next step on what should be done. We could suggest that user can perform `ballerina pull` or `ballerina use`.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by warunalakshitha** [comment]
We have fix ballerina dist list and some other commands with https://github.com/ballerina-platform/ballerina-distribution/pull/302. We need check other commands hence keeping without closing. Anyway this is now not a blocker since list command is fixed and still user can use --help any mememt.

**Comment by warunalakshitha** [comment]
Closing since dist command has direction text now.
