### ISSUE TITLE
Test cases for `ballerina update`

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#297]
**Description:**
Following scenarios **should** be tested for `ballerina update` command

1. My current version is 0.8.0, and there are no new versions available -> Nothing to update.
2. My current version is 0.8.0, and there is only 0.8.1 available -> Update to 0.8.1 successfully.
    - This involves two scenarios to verify.
    (i) Update and replace only the ballerina command jar file
    (ii) Update and replace both ballerina command jar file and ballerina sh/bat file.
3. My current version is 0.8.0, and there are multiple new versions available (0.8.1, 0.8.2, 0.8.5, 0.9.0, 0.9.1, 1.0.0, 1.0.1) -> Update to the latest successfully, which is 1.0.1.
    - This also involves two scenarios to verify.
    (i) Update and replace only the ballerina command jar file
    (ii) Update and replace both ballerina command jar file and ballerina sh/bat file.
4. For all three scenarios, other ballerina commands should work without any issues after the update command update.
5. All the combination of OS should also be tested for these cases.

@warunalakshitha, @keizer619 , @hevayo , @Kishanthan , @hemikak , @anupama-pathirage , @shafreenAnfar, @sameerajayasoma

**Comment by warunalakshitha** [comment]
Tested with 0.8.0, 0.8.1, 0.9.0 and 1.0.0 versions.
