### ISSUE TITLE
Cannot give a custom installation directory

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-distribution#312]
Mac installer does not let me install Ballerina to a custom location.

**Comment by keizer619** [comment]
At the moment we don't let change the installation location for deb, rpm and pkg installers. Its only allowed for windows installers.

**Comment by keizer619** [comment]
Since installation location is fixed in MacOS and Linux operating systems i will be closing this issue. 
If there are any concerns please feel free to open
