### ISSUE TITLE
Improve "permissions" related output of `ballerina update` command

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-distribution#313]
→ ballerina dist help update
ballerina: current user does not have permissions to run the command

Current user does not have write permissions to Ballerina installation path /Library/Ballerina. Grant permission to the file path or run the command with user has write permission.

**Comment by MaryamZi** [comment]
[Updated this](https://github.com/ballerina-platform/ballerina-distribution/pull/386/files#diff-74e17647fb8ca1443b00e6ef90f30facR589) to "ballerina: permission denied: you do not have write access to '<Installation_Path>'", as discussed today.
