### ISSUE TITLE
`ballerina dist list` output is not ordered

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#315]
**Description:**

The output is not ordered according to released versions.

```
ballerina dist list
Distributions available locally: 

  jballerina-1.1.0-alpha
  jballerina-1.0.2
  jballerina-1.0.4
* jballerina-1.0.3
  jballerina-1.1.0-beta

Distributions available remotely: 

  jballerina-1.0.0
  jballerina-1.0.1

```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Fixed
https://github.com/ballerina-platform/ballerina-distribution/pull/346/commits/06afedd65ca5a3770e1424a9ba5d70e89434f77e
