### ISSUE TITLE
verify output text `ballerina update`

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#316]
**Description:**

```
sudo ballerina update
Fetching latest version from remote server...
You are already in latest command version: 0.8.1

```

Especially, `You are already in latest command version: 0.8.1` 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/369
