### ISSUE TITLE
Ballerina dist remove generates too many logs

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-distribution#318]
**Description:**
Tried `>ballerina dist remove jballerina-1.0.4` command without non-admin cmd. I expect command to fail. Command failed. But reported a lot of logs. 

output:
```
>ballerina dist remove jballerina-1.0.4
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
jballerina-1.0.4 cannot remove
Terminate batch job (Y/N)? y
```

Tested on JBallerina-1.1.0-Beta

**Comment by Kishanthan** [comment]
Similar to - https://github.com/ballerina-platform/ballerina-distribution/issues/266

**Comment by pubudu91** [comment]
Issue seems to be in the way failed file removals are handled. See https://github.com/ballerina-platform/ballerina-distribution/blob/84b97a78115905b851e0d60611171d990d8e80b4/ballerina-command/src/main/java/org/ballerinalang/command/cmd/RemoveCommand.java#L139

**Comment by keizer619** [comment]
Same issue is reported 
https://github.com/ballerina-platform/ballerina-distribution/issues/266
