### ISSUE TITLE
`dist` command allows to remove all distribution from locally, which cause other commands to fail

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-distribution#319]
Steps to reproduce

* Remove all distribution using `ballerina dist remove <version>`.
* Try `ballerina version` or `ballerina build` command. 
* Command fails, with following. 

```
>ballerina version
The system cannot find the path specified.
Command 0.8.0

>ballerina build hello.bal
The system cannot find the path specified.
```

Tested with JBallerina-1.1.0-beta

**Comment by hasithaa** [comment]
After Discussing with @keizer619, I got to know ballerina dist requires to have at least one distribution locally. So remove command should not delete all distributions, which is the actual bug.

**Comment by keizer619** [comment]
This happens as current versions is coming from user home. We are checking the existence of that version in the router level. So i have another checking in the command execution as well.
 https://github.com/ballerina-platform/ballerina-distribution/pull/356/commits/e964ad78117cb732f0a39e05e6abf183126d6f13
