### ISSUE TITLE
Update output text of `ballerina dist update` in wrong for already updated scenario

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#320]
**Description:**

```
$ sudo ballerina dist update
Fetching latest distribution version from remote server...
Already in latest distribution version: 1.0.4

```

It says `Already in latest distribution version: 1.0.4` which is wrong. It has to say jballerina-1.0.4

The same issue is there for below scenario as well.

```
$ sudo ballerina dist update
Fetching latest distribution version from remote server...
Updated to latest distribution version: 1.0.4
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/369
