### ISSUE TITLE
Remove `ballerina fetch` command as it needs to be finalized

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#321]
**Description:**
$subject. Lets not ship this for 1.1.0 as it needs more thinking.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Fixed in following PR
https://github.com/ballerina-platform/ballerina-distribution/pull/343/files
