### ISSUE TITLE
Example in `ballerina dist remove` help text is wrong

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-distribution#322]
When you run `ballerina dist remove --help`, the examples section in the help text gives the following example:
```
EXAMPLES
     Remove Ballerina 1.0.0 version.
        → ballerina remove 1.0.0
```
This should've been `ballerina dist remove 1.0.0`

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/329
