### ISSUE TITLE
Output of `ballerina help` shows "Update Tool Commands:"

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#323]
**Description:**
The output of help command on update section shows like this.

```
   Update Tool Commands:
        dist            Commands for Ballerina distribution version management
        update          Update the Ballerina command

```
We decided to use "Update Commands:" instead. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/329
