### ISSUE TITLE
Typo caused Ballerina command to fail with  `too many arguments given` error

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-distribution#325]
Tried this command by mistake 
```
>ballerina dist lsit
ballerina: too many arguments given
Run 'ballerina help' for usage.
```

The correct command works fine. 
```
>ballerina dist list
Distributions available locally:

  jballerina-1.1.0-beta

Distributions available remotely:

  jballerina-1.0.0
  jballerina-1.0.1
  jballerina-1.0.2
  jballerina-1.0.3
  jballerina-1.0.4

Run 'ballerina dist pull <version>' to pull distributions available remotely
Run 'ballerina dist use <version>' to use distributions available locally
```

**Comment by pubudu91** [comment]
I guess we can change the error message here to something like: `unrecognized command 'lsit'`. The `too many arguments given` error message would only be valid for commands like `run`, `build`, `test` etc. I guess.

**Comment by keizer619** [comment]
Fixed to show like `ballerina: unknown command 'lsit'` just like in ballerina command 
https://github.com/ballerina-platform/ballerina-distribution/pull/344/commits/8218c4dfb1afd52ef74a813979ffb64077b2d822
