### ISSUE TITLE
`ballerina dist -h` does not show the help of dist command

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#326]
**Description:**
Currently it shows like this.

```
$ ballerina dist -h    

   Update Tool Commands:
        dist            Commands for Ballerina distribution version management
        update          Update the Ballerina command


See 'ballerina help <command>' for more information on a specific command.
```

Same issue is there with `ballerina dist --help` option too.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/329
