### ISSUE TITLE
Wrong error message when a wrong version is given to `bal dist use`

### ISSUE THREAD

**Issue by Dilhasha** [ballerina-platform/ballerina-distribution#3267]
**Description:**
Please see the below screenshot where I accidentally gave a wrong version. I've noticed an error message saying `distribution not found` when given other non-existant versions. But, looks like this `2201.1.1.` with trailing period breaks some other internal validation resulting in an internal server error. 

<img width="634" alt="image" src="https://user-images.githubusercontent.com/5234641/193601868-c1b7566d-f61e-491c-bcb2-31a110ec5b33.png">

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by keizer619** [comment]
Now we are getting an output like this. Hence I will be closing this

```
Distribution '2201.1.1.' not found
'2201.1.1.' is not a valid distribution. Use 'bal dist list -a' for the available distributions list
```
