### ISSUE TITLE
Output of `ballerina dist list --help` is not aligned

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#327]
**Description:**

```
$ ballerina dist list --help
NAME
    ballerina-dist-list - List available Ballerina distributions

SYNOPSIS
    ballerina dist list

DESCRIPTION
     Ballerina dist list lists available Ballerina distributions.

EXAMPLES
     List available Ballerina versions.
        → ballerina dist list
```

Let's check all the subcommands out for correct alignment. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/329
