### ISSUE TITLE
Review and verify output of `ballerina dist pull --help`

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#328]
**Description:**
```
$ ballerina dist pull --help
NAME
       ballerina-dist-pull - Pull and use a given distribution version

SYNOPSIS
       ballerina dist pull <distribution-version>


DESCRIPTION
       Dist-pull pulls and uses a given Ballerina version from project repository.


OPTIONS
       Ballerina dist pull command takes no options.


EXAMPLES
       Install Ballerina 1.0.0 version.
          → ballerina dist pull jballerina-1.0.0

       This will download and keep jballerina-1.0.0 distribution and set ballerina command.
```

Issues
1. Fix grammer issues in 
`DESCRIPTION
       Dist-pull pulls and uses a given Ballerina version from project repository.`
2. Fix this text `This will download and keep jballerina-1.0.0 distribution and set ballerina command.` This setance does not have a meaning IMO.
3. Remove the OPTIONS as if the command does not take any, its no point showing that in the text.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/329
