### ISSUE TITLE
Proper error message not given for instances where there isn't a Ballerina distribution

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-distribution#330]
Try running a command when there are no Ballerina distributions locally. For example,
```
$ ballerina fetch
/usr/lib/ballerina/bin/ballerina: line 56: /usr/lib/ballerina/bin/../distributions/jballerina-1.1.0-beta/bin/./ballerina: No such file or directory
```
This should've given a proper error message stating that a Ballerina distribution could not be found.

**Comment by keizer619** [comment]
This is happened due to bug in the it allows to delete all the versions including active one. We have fixed that issue, so this issue won't happen unless you delete directories manually.
