### ISSUE TITLE
Generic help message given for incorrect usages of commands

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-distribution#331]
Consider the following for example:
```
$ ballerina dist fetch
ballerina: distribution is not provided
Run 'ballerina help' for usage.
```
The above should've ideally suggested to run `ballerina dist fetch --help` or `ballerina help dist fetch` instead of the general help, `ballerina help`.

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/357
