### ISSUE TITLE
Output of `ballerina dist use --help` is not aligned

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#332]
**Description:**

```
$ ballerina dist use --help 
NAME
    ballerina-dist-use - Use a given distribution version

SYNOPSIS
    ballerina dist use <distribution-version>

DESCRIPTION
     Use pulls and uses a given Ballerina version from project repository.

OPTIONS
     Ballerina dist use command takes no options.

EXAMPLES
     Use Ballerina 1.0.0 distribution.
        → ballerina dist use jballerina-1.0.0

```

Issues
1. Not aligned.
2. OPTIONS is not needed.
3. The text should say that this will switch and use the given version as the default version.

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/329
