### ISSUE TITLE
Output of `ballerina dist update --help` is not aligned

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#334]
**Description:**
```
$ ballerina dist update --help
NAME
    ballerina-dist-update - Update to latest distribution version

SYNOPSIS
    ballerina dist update

DESCRIPTION
     Ballerina dist update command updates to latest version.

OPTIONS
     Ballerina dist update command takes no options.

EXAMPLES
     Update current distribution to latest.
        → ballerina dist update

```
Issues
1. Not aligned.
2. OPTIONS is not needed.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/329
