### ISSUE TITLE
Output of `ballerina dist remove --help` is not aligned

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#336]
**Description:**
```
$ ballerina dist remove --help
NAME
    ballerina-remove - Remove a given distribution version

SYNOPSIS
    ballerina dist remove <distribution-version>

DESCRIPTION
     removes the given Ballerina version from project repository.

OPTIONS
     Ballerina dist remove command takes no options.

EXAMPLES
     Remove Ballerina 1.0.0 version.
        → ballerina remove 1.0.0
```

Issues
1. Not aligned.
2. OPTIONS is not needed.
3. Description sentence text starts with lowercase like `removes the given Ballerina version from project repository.`. 
4. Examples cmd says `ballerina remove 1.0.0`, which is wrong. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/329
