### ISSUE TITLE
`dist remove <non-existing-name>` output error is wrong

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#337]
**Description:**
```
$ sudo ballerina dist remove eoihgient
Password:
eoihgient does not exist
```

The error is not a ballerina type error. Something like `ballerina: some text`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Fixed
https://github.com/ballerina-platform/ballerina-distribution/pull/346/commits/3781637f4e88db2ed6895bcbf5ba5d1cf41a0c68
