### ISSUE TITLE
Debug level info exposed as error messages to the user

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-distribution#338]
Consider the following:
https://github.com/ballerina-platform/ballerina-distribution/blob/fb17fe2fdef2bc20a15c7509fe26f931808960c0/ballerina-command/src/main/java/org/ballerinalang/command/util/ToolUtil.java#L245
There is little use in printing this as a standard error message from the CLI tool right? This prints the JSON it received as well.

**Comment by warunalakshitha** [comment]
Currently We not support logger stuff. May be we can add them next release to enable debug logs.
IMO it is ok to print the json FTM if not debugging those errors would be hard in the future. I think this is not blocker hence reduce the severity.

**Comment by warunalakshitha** [comment]
Related issue https://github.com/ballerina-platform/ballerina-distribution/issues/333

**Comment by warunalakshitha** [comment]
Updated the message with https://github.com/ballerina-platform/ballerina-distribution/pull/343.
We will add debug option with https://github.com/ballerina-platform/ballerina-distribution/issues/333
