### ISSUE TITLE
`ballerina dist <unknown-subcmd>` does not shoe the correct error

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#339]
**Description:**
```
$ ballerina dist zzzzzzzzz
ballerina: too many arguments given
Run 'ballerina help' for usage.
```

The above output should say unknown command or related log message.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
Fixed
https://github.com/ballerina-platform/ballerina-distribution/commit/8218c4dfb1afd52ef74a813979ffb64077b2d822
