### ISSUE TITLE
README and INSTALL guide files for distribution

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#340]
**Description:**
Following are the steps to include in the INSTALL guide.

- For 1.1.0 release, the zip based distribution will not ship JRE by default.
- Users will be guided to download the required JRE from [AdoptOpenJDK](https://adoptopenjdk.net/releases.html) which Ballerina installers are also shipping.
- The steps are as follows, when a user starts from the zip based approach.
  - script/bat file will check for JRE availability under dependencies directory.
  - If one found, use it.
  - If not, check whether java 8 is available in the system.
  - If found, use it.
  - Else, inform the user about the unavailability of java and direct the user to the user guide on how to download specific JRE for the OS/Arch. 
- We will recommend to use JRE from [AdoptOpenJDK](https://adoptopenjdk.net/releases.html).
- The user guide has to be created for these steps.

**Comment by pubudu91** [comment]
Added with #370 and #406. Hence closing this.
