### ISSUE TITLE
Transaction integration test doesn't run in the build and test is invalid

### ISSUE THREAD

**Issue by pcnfernando** [ballerina-platform/ballerina-distribution#3414]
**Description:**
https://github.com/ballerina-platform/ballerina-distribution/blob/master/stdlib-integration-tests/transaction/tests/xa_transactions_test.bal

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by KavinduZoysa** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/5270
