### ISSUE TITLE
The publish release Windows Installer Build is failing

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-distribution#3446]
**Description:**
Workflow run - https://github.com/ballerina-platform/ballerina-distribution/actions/runs/3487015925/jobs/5835307336#step:5:41

This was found when publishing 2201.3.0-rc2

**Comment by NipunaMadhushan** [comment]
This happens due to a latest version update in dotnet-guid and it doesn't compatible with dotnet version `2.1.x`.
