### ISSUE TITLE
Unnecessary new line in the description text

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3462]
**Description:**

Refer below image. It is there in most BBEs

**Example 1:** 

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/16300038/202540578-5946e8f8-845f-4724-b3ad-3f668768afdd.png">

**Example 2:**

Refer [Status code response records](https://pre-prod.ballerina.io/learn/by-example/http-status-code-record/) BBE 

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/16300038/202568024-5e93e437-fa0e-49ea-a502-5455195d0143.png">

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3509/files#diff-27fad123632c071a1a3472fb84864334634e51704f34d1af11d13b1b87649a9bR3 in all HTTP BBEs
