### ISSUE TITLE
Issues in `Basic REST API` BBE description

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3464]
**Description:**

1. Why only `accessor-name` is highliged as code.
2. Unncessary new line in between `support helps to write meaningful` and `APIs`. 
3. Missing full stop in the sentence `The sample depicts the way of writing GET and POST resources`.
4. Why the reference to specification is not there. It was added to other HTTP BBEs.
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/16300038/202541634-7402bcfc-70aa-4423-afb0-d3e8be795522.png">

[1] https://pre-prod.ballerina.io/learn/by-example/http-basic-rest-api/

**Comment by chamil321** [comment]
> **Description:**
> 
> 1. Why only `accessor-name` is highliged as code.
Added to other constucts

> 2. Unncessary new line in between `support helps to write meaningful` and `APIs`.
The newlines in md file has created this gap. Hence the description is brought into a single line without newlines.

> 3. Missing full stop in the sentence `The sample depicts the way of writing GET and POST resources`.
Added

> 4. Why the reference to specification is not there. It was added to other HTTP BBEs.
The specification link is added to some BBEs if there are any more information available in the spec to refer. The spec does not contain anything specifically on REST. Therefore it was not added. However we can link the https://ballerina.io/spec/http/#23-resource section as it contains REST constructs such as HTTP verb, path, query and all.

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3566
