### ISSUE TITLE
Code is having warinings in `Basic REST API` BBE

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3465]
**Description:**

IMO we should write small samples which doesn't have warnings. Otherwise users will tend to write similar codes and they won't understand how to fix those.

`Basic REST API` sample [1] gives the below warnings

`attempt to expose non-public symbol 'Album'`
`concurrent calls will not be made to this method since the method is not an 'isolated' method`

<img width="710" alt="image" src="https://user-images.githubusercontent.com/16300038/202542345-4c07a385-12d1-434e-80ba-640a377f07c0.png">

[1] https://pre-prod.ballerina.io/learn/by-example/http-basic-rest-api/

**Comment by sameerajayasoma** [comment]
Here is my original idea. I already talked to @shafreenAnfar  and @chamil321 last week about this. It was rejected for some reason :) 

```ballerina
import ballerina/io;
import ballerina/http;

type Album readonly & record {|
    string title;
    string artist;
|};

service / on new http:Listener(9090) {
    resource function get albums() returns Album[] {
        return [
            {title: "Blue Train", artist: "John Coltrane"},
            {title: "Jeru", artist: "Gerry Mulligan"}
        ];
    }

    resource function post albums(@http:Payload Album album) returns Album {
        io:println(string `Adding album: ${album.title} by ${album.artist}`);
        return album;
    }
}

```

**Comment by sameerajayasoma** [comment]
We can even remove the post resource here. just get is enough

**Comment by chamil321** [comment]
The mentioned issue has been fixed for update 3. Please check https://github.com/ballerina-platform/ballerina-lang/issues/38460
Hence i kept it without making the record public.
