### ISSUE TITLE
Formatting issues in samples

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3466]
**Description:**

Check $subject in all samples.

E.g. in https://pre-prod.ballerina.io/learn/by-example/http-basic-rest-api/

<img width="802" alt="image" src="https://user-images.githubusercontent.com/16300038/202543034-fd02cc01-630b-4ce6-87e7-e1dbc428af7a.png">

Another example [Status code response records](https://pre-prod.ballerina.io/learn/by-example/http-status-code-record/) BBE

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3590
