### ISSUE TITLE
Code comments should be valid English sentences.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3468]
**Description:**

$subject and check the punctuation as well. Found full stop is missing in most cases.

<img width="798" alt="image" src="https://user-images.githubusercontent.com/16300038/202544521-5abb6e21-ed39-4b02-80ae-84d15c56b456.png">

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3590
