### ISSUE TITLE
Can we avoid URLs in code comments

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3471]
**Description:**

$subect in [1]. Since we have the ability to write detailed descriptions we can move the URLs to the relevant text in the description.

[1] https://pre-prod.ballerina.io/learn/by-example/http-data-binding/

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/16300038/202551604-f9f5625a-3f7a-4c83-8ae8-38f8a244e582.png">

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3566
