### ISSUE TITLE
Missing code highlighes in `Path parameter` BBE

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3472]
**Description:**

$subject in [1]

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/16300038/202554188-34f4483b-6d92-4a71-97f2-ca7ceb0942c2.png">

[1] https://pre-prod.ballerina.io/learn/by-example/http-path-param/

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3539/files#diff-cfc984ced7c14532874f2b799229963f5c4cf85a6fa175a29b7d56fc8e64825fR3
