### ISSUE TITLE
Simplify the `if else` block in `Path parameter` BBE

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3473]
**Description:**
$subject in [1]

Existign code:

```bal
        if album is () {
            return http:NOT_FOUND;
        } else {
            return album;
        }
```

Suggestion:

```bal
        if album is () {
            return http:NOT_FOUND;
        } 
        return album;
```

[1] https://pre-prod.ballerina.io/learn/by-example/http-path-param/

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3509/files#diff-83134a504c7729ef6f102d5fbb0e4a2c1f13af0bc6a9ee6fb35c9e73a98373f4R22
