### ISSUE TITLE
Incorrect cURL command in `Path Parameter` BBE

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3474]
**Description:**

$subject in [1]

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/16300038/202555505-5b5e6f66-d9d7-488a-b543-3d1f03a12bab.png">

[1] https://pre-prod.ballerina.io/learn/by-example/http-path-param/

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3509/files#diff-3ad7f2787ecdb97fbc6ef7f1ce5ec94284fde260e1939b5caa89a6087edeffe5R1
