### ISSUE TITLE
Use the example used in the `Basic REST API` in all of HTTP BBEs, if applicable. 

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-distribution#3475]
See: https://pre-prod.ballerina.io/learn/by-example/http-service-ssl-tls/

We've used `/foo/bar` service here, we could have used the `/album` service easily.

**Comment by chamil321** [comment]
@shafreenAnfar Should we bring another secured listener to be used in security BBEs? Something similar to [HTTPS Listener](https://pre-prod.ballerina.io/1.2/learn/by-example/https-listener.html)

**Comment by chamil321** [comment]
Re-arranged `HTTP service security` and `HTTP client security` BBEs to the `Album` theme via PR https://github.com/ballerina-platform/ballerina-distribution/pull/3589

**Comment by chamil321** [comment]
This is completed, therefore closing the issue
https://pre-prod.ballerina.io/learn/by-example/http-service-ssl-tls/
