### ISSUE TITLE
Missing code highlights in `Query parameter` BBE

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3477]
**Description:**

$subject in [1]

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/16300038/202559145-45509cca-5fd4-4b7e-8741-943da702b98d.png">

[1] https://pre-prod.ballerina.io/learn/by-example/http-query-parameter/

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3566
