### ISSUE TITLE
Be consistent in `percent-and-newline` character in the cURL output

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3478]
**Description:**
$subject.

In some BBEs, e.g. [Path parameter](https://pre-prod.ballerina.io/learn/by-example/http-path-param/) `%` is not shown in the output.

But some BBEs e.g. [Query parameter](https://pre-prod.ballerina.io/learn/by-example/http-query-parameter/) it is shown.

Need to be consistent. 

<img width="783" alt="image" src="https://user-images.githubusercontent.com/16300038/202561086-2b89cd19-d369-4a2f-94f0-87c20e4c3956.png">

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3566
