### ISSUE TITLE
Have consistent approach in representing response codes

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3479]
Refer [Header Parameter](https://pre-prod.ballerina.io/learn/by-example/http-header-param/) BBE:

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/16300038/202561787-502c8feb-33a7-45ef-8e7b-ac2ebc5eb54a.png">

Refer [Service data binding](https://pre-prod.ballerina.io/learn/by-example/http-data-binding/) BBE:

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/16300038/202561932-c111a153-6899-444c-a48f-db66e82799ae.png">

**Comment by chamil321** [comment]
Remove the unnecessary formatting via https://github.com/ballerina-platform/ballerina-distribution/pull/3539/files#diff-2ec00a849bb322bc563cd93c8dfa26dbb280987d20d2aeaeed5ac65fce3909c3R3

**Comment by chamil321** [comment]
Closing the issue as this is fixed now
https://github.com/ballerina-platform/ballerina-distribution/issues/3479
