### ISSUE TITLE
The command output messages, CLI help texts don't reflect what the update command really does

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-distribution#351]
When I heard about the `ballerina dist update` command, I assumed it updates to the latest version of Ballerina available. But now only I got to know that that is not the case. It only updates to the latest patch version. However, this precise notion of what the update command does it not reflected in the CLI help text. Even in the outputs of the command messages, in some places it refers to the patch version, and in some places it simply refers to as the latest Ballerina version. IMO, this could be confusing. We need to update the docs to include precisely what the update command does. We also need to update the outputs of the commands to convey precisely what it did. When I saw the references to the latest Ballerina version in the command outputs, I assumed it referred to the latest release done by the Ballerina team.

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/355
