### ISSUE TITLE
Verify output of `ballerina update`

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#352]
**Description:**
```
$ sudo ballerina update
Password:
Fetching latest version from remote server...
You are already in latest command version: 0.8.1
```

There are grammer issues with both the sentences above.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/355
