### ISSUE TITLE
Should we log HTTP error codes in the output ?

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#354]
**Description:**

Check the following scenario.

```
➜  ~ ballerina dist use jballerina-1.1.0-beta
Using distribution version: jballerina-1.1.0-beta

➜  ~ sudo ballerina dist update              
Fetching latest distribution version from remote server...
ballerina: server request failed. HTTP error code 404
```

The error is logged with 404 code. It is not useful for the user IMO. There are other places also in the codebase which logs HTTP error codes.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/361.
