### ISSUE TITLE
[SOLARIS] ballerina command does not work due to grep incompatibility.

### ISSUE THREAD

**Issue by dulvinw** [ballerina-platform/ballerina-distribution#359]
**Description:**
By default solaris grep does not support -e switch. Therefore trying to run bin/ballerina fails for each command. 

Work around I tried is to use the /usr/xpg4/bin/grep as the system default in solaris. That version of grep supports -e switch.

**Suggested Labels:**
BLOCKER

**Suggested Assignees:**
@keizer619 

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
SOLARIS 11

**Steps to reproduce:**

**Related Issues:**

**Comment by gimantha** [comment]
fixed with https://github.com/ballerina-platform/ballerina-lang/pull/20463
