### ISSUE TITLE
Inconsistent version info given when the Java version is not 8

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-distribution#367]
When the Java version used is not 8 (my `JAVA_HOME` variable was set to 9), and you try to run `ballerina version`, you get the following:
```
$ ballerina version
Error: Ballerina is supported only on JDK 1.8
Command 0.8.0
```
Isn't this sorta of wrong? The unsupported Java version error message is given, then the version of the command is still printed.

Also, is it correct to say Ballerina is only supported on JDK 1.8? We don't need the JDK to run Ballerina right? Just the JRE?

**Comment by Kishanthan** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/370
