### ISSUE TITLE
Grammer and text issues

### ISSUE THREAD

**Issue by Kishanthan** [ballerina-platform/ballerina-distribution#368]
**Description:**
1. `dist update - The latest patch version '1.0.5' is already the active version`. This has the number only. It should include jballerina-1.0.5 whole text.
```
$ ./bin/ballerina dist update
Fetching the latest patch version for distribution version '1.0.5' from the remote server...
The latest patch version '1.0.5' is already the active version
```
2. `dist pull - Fetching distribution from remote server...`. Grammer issues in this statement.
```
$ ./bin/ballerina dist pull jballerina-1.0.5
Fetching distribution from remote server...
```

3. `dist pull - Next step guide is not consistent with the help text`. We should say `Run 'ballerina dist pull <distribution-version>' to pull distributions available remotely`.
```
$ ./bin/ballerina dist list                 
Distributions available locally: 

  jballerina-1.1.0-beta2
* jballerina-1.0.5

Distributions available remotely: 

  jballerina-1.0.4
  jballerina-1.0.3
  jballerina-1.0.2
  jballerina-1.0.1
  jballerina-1.0.0

Run 'ballerina dist pull <version>' to pull distributions available remotely
Run 'ballerina dist use <version>' to use distributions available locally
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/369
