### ISSUE TITLE
Improve BBEs related to  `Conditional statements`

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-distribution#3700]
**Description:**

Improve currently available BBEs related to `Conditional statements`

- [ ] [Booleans and conditionals](https://ballerina.io/learn/by-example/booleans/)
- [ ] [Match statement](https://ballerina.io/learn/by-example/match-statement/)

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/3871
