### ISSUE TITLE
Improve BBEs related to `iteration`

### ISSUE THREAD

**Issue by DamithaSenevirathne** [ballerina-platform/ballerina-distribution#3701]
**Description:**

Improve BBEs related to iteration

- [ ] [Foreach statement](https://ballerina.io/learn/by-example/foreach-statement/)
- [ ] [While statement](https://ballerina.io/learn/by-example/while-statement/)

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/3910
