### ISSUE TITLE
[Windows] Invalid char in help text

### ISSUE THREAD

**Issue by hasithaa** [ballerina-platform/ballerina-distribution#371]
Getting following output in windows. Terminal char is not rendering properly in windows cmd. 

```
> ballerina help update
NAME
       ballerina-update - Update to the latest Ballerina command version

SYNOPSIS
       ballerina update


DESCRIPTION
       Update updates the Ballerina command to the latest version.


EXAMPLES
       Update the Ballerina command to the latest version.
          ? ballerina update
```

**Comment by MaryamZi** [comment]
Changed this to `$` in the ballerina-distribution commands, with https://github.com/ballerina-platform/ballerina-distribution/pull/386, as discussed offline with @hasithaa and @Kishanthan.

Will send a separate PR for the lang repo commands.
