### ISSUE TITLE
When there are multiple curl commands split them to two

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3734]
**Description:**

When there are multiple curl commands to try, can we split them into two boxes?  Otherwise copy button will copy only the first command. 

And need to update the text properly as well with some info about the two commands.

E.g. https://ballerina.io/learn/by-example/http-basic-rest-service/

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/16300038/205975048-76fb3468-a818-4ebc-9852-25ecd871db3e.png">

**Comment by keizer619** [comment]
<img width="1313" alt="Screenshot 2023-09-15 at 11 42 52" src="https://github.com/ballerina-platform/ballerina-distribution/assets/2918812/fed0f19e-7043-413d-8b59-fc56c6be2bbc">

These have been fixed by now
