### ISSUE TITLE
Links to othe BBEs are not valid in some examples

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3735]
**Description:**

$subject. Maybe as the BBE titles were changed after referencing them. Since those are not valid the links are returning to BBE landing page. 

Check all BBE links.

E.g. https://ballerina.io/learn/by-example/http-service-payload-constraint-validation/

Pointing to invalid link : https://ballerina.io/by-example/constraint-validations/

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/16300038/205979478-cc6ee30a-4fc7-44e6-95d0-f88163b63c00.png">

Another example:

In https://ballerina.io/learn/by-example/http-caching-client/ , the link given for [Sending cache response service](https://ballerina.io/learn/by-example/http-caching-client/learn/by-example/http-service-cache-response/) under prerequisites is invalid.

**Comment by praneesha** [comment]
Both of the above occurrences are fixed now. All BBEs will be checked via the ongoing content review hackathons.
