### ISSUE TITLE
ballerina version [--help | -h ] shows "unknown help topic `version`"

### ISSUE THREAD

**Issue by grainier** [ballerina-platform/ballerina-distribution#376]
**Description:**
$title. `ballerina version [--help | -h ]` will show "ballerina: unknown help topic `version`
Run 'ballerina help' for usage." at the end. 

**Affected Product Version:**
1.1.0-beta2

**OS, DB, other environment details and versions:**    
Mac, Zip

**Steps to reproduce:**
`ballerina version [--help | -h ]`

**Comment by KavinduZoysa** [comment]
The same error occurs for `ballerina help dist remove` command fro CentOS.

![remove](https://user-images.githubusercontent.com/28332708/71082395-0b44a000-21b7-11ea-86c3-ccfc283cb55f.png)

**Comment by MaryamZi** [comment]
Fixed with #383
