### ISSUE TITLE
[Windows] Ballerina version doesn't update with pull and use command

### ISSUE THREAD

**Issue by daneshk** [ballerina-platform/ballerina-distribution#379]
**Description:**
In windows, Ballerina version doesn't get update when we execute `ballerina dist pull` and `ballerina dist use` commands.

**Affected Product Version:**
ballerina 1.1.0-beta2

**OS, DB, other environment details and versions:**    
Windows 8.1

**Steps to reproduce:**

![ballerina_update](https://user-images.githubusercontent.com/8402398/71080431-244b5200-21b3-11ea-92a9-ba370fbcbf7b.PNG)

**Comment by keizer619** [comment]
Fixed in here
https://github.com/ballerina-platform/ballerina-distribution/pull/387
