### ISSUE TITLE
ballerina help update command do not show the Help documentation

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-distribution#380]
**Description:**
Execute the `ballerina help update`.
Following is prompted except the expected help documentation

**ballerina: unknown help topic `update`
Run 'ballerina help' for usage.**

**Comment by Kishanthan** [comment]
This happens when you update to 0.9.0 on command and then try to run `ballerina help update`

**Comment by Kishanthan** [comment]
Basically, none of the dist related help commands are working after using 0.9.0.

```
➜  ~ ballerina help dist list  
ballerina: unknown help topic `list`
Run 'ballerina help' for usage.
➜  ~ ballerina help dist pull
ballerina: unknown help topic `pull`
Run 'ballerina help' for usage.
➜  ~ ballerina help dist list
ballerina: unknown help topic `list`
Run 'ballerina help' for usage.
➜  ~ ballerina help dist remove
ballerina: unknown help topic `remove`
Run 'ballerina help' for usage.
➜  ~ ballerina help dist use   
ballerina: unknown help topic `use`
Run 'ballerina help' for usage.
```

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/383
