### ISSUE TITLE
Broken links in `Azure functions` BBE

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3813]
**Description:**
$subject in [1] in two places

[1] https://ballerina.io/learn/by-example/azure-functions-deployment/

![screencapture-ballerina-io-learn-by-example-azure-functions-deployment-2022-12-14-16_14_35](https://user-images.githubusercontent.com/16300038/207726718-35ae5e9c-f1bb-4cd7-998d-60ee0ea5d4f3.png)

**Comment by xlight05** [comment]
Fixed the issue with above PR.
Had a chat with @praneesha . Earlier website supported redirects with `redirect_from` field in learn pages. Seems like the new nextJS site does not support those redirects, thats why it was broken. 
Made an issue to remove `redirect-from` from .md files.
https://github.com/ballerina-platform/ballerina-dev-website/issues/6069
