### ISSUE TITLE
Broken links in `AWS lambda` BBE

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3814]
**Description:**
$subject in [1] in 3 places

![screencapture-ballerina-io-learn-by-example-aws-lambda-deployment-2022-12-14-16_12_40](https://user-images.githubusercontent.com/16300038/207726434-6ec6f6eb-2a1b-4d22-adb4-f0c0b3f92fb8.png)

[1] https://ballerina.io/learn/by-example/aws-lambda-deployment/

**Comment by xlight05** [comment]
Fixed the issue with above PR.
Had a chat with @praneesha . Earlier website supported redirects with `redirect_from` field in learn pages. Seems like the new nextJS site does not support those redirects, thats why it was broken. 
Made an issue to remove `redirect-from` from .md files.
https://github.com/ballerina-platform/ballerina-dev-website/issues/6069
