### ISSUE TITLE
Remove  rc part from directory in artifact server during artifact publish

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-distribution#3819]
**Description:**
Remove  rc part from directory in artifact server during artifact publish

**Comment by NipunaMadhushan** [comment]
It seems that we don't use rc part of the version even now.  
https://github.com/ballerina-platform/ballerina-distribution/blob/master/.github/workflows/publish-release-artifacts.yml#L149
https://github.com/ballerina-platform/ballerina-distribution/blob/master/.github/workflows/publish-release-artifacts.yml#L149
