### ISSUE TITLE
Un-installing beta and installing beta2 resulted in below error

### ISSUE THREAD

**Issue by shafreenAnfar** [ballerina-platform/ballerina-distribution#382]
**Description:**

After installing ballerina when I do ballerina -v. I get the below.

/usr/bin/ballerina: line 76: /usr/lib/ballerina/bin/../distributions/jballerina-1.1.0-beta/bin/./ballerina: No such file or directory
Command 0.8.0

**Comment by keizer619** [comment]
I tried in an ubuntu machine by installing beta and reinstalling beta2, but unfortunately could not reproduce the issue.

**Comment by keizer619** [comment]
This is not reproduce i am closing this, if there are any concerns please feel free to reopen
