### ISSUE TITLE
Need to review the info message when pulling already existing named distribution

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-distribution#388]
**Description:**
Need to review the info message when pulling already existing named distribution.

For instance; if I try to pull and already existing distribution it prints below info message.

![Capture](https://user-images.githubusercontent.com/1448489/71099009-997d4e00-21d8-11ea-84f2-946269423232.PNG)

Which is similar to the `ballerina dist use jballerina-x.x.x`.
![Capture2](https://user-images.githubusercontent.com/1448489/71099236-f8db5e00-21d8-11ea-8660-19a5a236827d.PNG)

As per the docs, the expectation of the `pull` is to download the named dist and set to current version. If it already downloaded it will be nice to inform the user that distribution is not downloaded again. For instance, something like belows;

`Distribution 'jballerina-x.x.x' is already downloaded, Using distribution version: jballerina-x.x.x`

**Comment by MaryamZi** [comment]
Fixed with #403.

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/403
