### ISSUE TITLE
[HTTP Client] Use open records in the client side

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-distribution#3924]
Some of the current http client examples use closed records now. 
https://ballerina.io/learn/by-example/http-client-send-request-receive-response/

```
mport ballerina/http;
import ballerina/io;

type Album readonly & record {|
    string title;
    string artist;
|};
...
```

Is there any particular reason to use closed records?

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/pull/3925
