### ISSUE TITLE
`ballerina update` help text shows `ballerina dist update` help text

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-distribution#397]
**Description:**
$title

<img width="926" alt="Screen Shot 2019-12-19 at 10 46 28 AM" src="https://user-images.githubusercontent.com/24229626/71146856-daaf4580-224c-11ea-81f4-a91b58a8d9af.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
0.8.1 (in RC1 pack)

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by MaryamZi** [comment]
Fixed with https://github.com/ballerina-platform/ballerina-distribution/pull/398
