### ISSUE TITLE
The platform distribution contains tools distribution version as the version

### ISSUE THREAD

**Issue by dilinisg** [ballerina-platform/ballerina-distribution#4]
**Description:**
The platform distribution contains tools distribution version as the version in /bin/version file.

**Suggested Labels:**
Bug

**Affected Product Version:**
beta-0

**OS, DB, other environment details and versions:**   
Pack downloaded from the Windows installer

**Comment by keizer619** [comment]
We don't include version.txt anymore inside bin. Hence closing this issue
