### ISSUE TITLE
The --skip-tests option is shown as unknown option.

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#401]
**Description:**

Although it says unknown option, the tests are skipped without any issue.
 
<img width="415" alt="image" src="https://user-images.githubusercontent.com/16300038/71152900-b7d95d00-225d-11ea-938a-9b01af867aee.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
This is fixed
https://github.com/ballerina-platform/ballerina-distribution/pull/407
