### ISSUE TITLE
Ballerina update command gives success msg even it is interrupted

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-distribution#405]
**Description:**
Ballerina update command gives success message even it is interrupted.

**Steps to reproduce:**
1. Trigger `ballerina update` command.
2. Before command completes issue CTRL+C to interrupt the command
3. The command exists with `Update successfully completed`
4. Check Command version with `ballerina -v` it still the old one.

![Capture3](https://user-images.githubusercontent.com/1448489/71164256-b0717e00-2274-11ea-8d5c-03d2f487cb86.PNG)

**Comment by parkavi11** [comment]
This issue is fixed, hence can be closed.

**Comment by keizer619** [comment]
This has been fixed in 0.8.5 tool version. You can execute "ballerina update" command and update the tool version. Hence closing the issue
