### ISSUE TITLE
Decimal Type BBE throws a compile time error in Ballerina Playground 

### ISSUE THREAD

**Issue by SasinduDilshara** [ballerina-platform/ballerina-distribution#4061]
## Description
> [Decimal example](https://ballerina.io/learn/by-example/decimal-type.html) in Ballerina By examples throw a compile time error `unnecessary condition: expression will always evaluate to 'true'` in Ballerina Playground. This suppose to be a Hint by Ballerina compiler and it not suppose to fail in compile time. Same behaviour is observed when there are warnings as well.

## Steps to reproduce

![Screenshot 2022-06-28 at 13 13 30](https://user-images.githubusercontent.com/47134066/176122683-07a55484-3489-4071-a6cd-90470ff05f67.png)

## Related website/documentation area
Area/BBEs

## Suggested label(s) (optional)
Bug

**Comment by keizer619** [comment]
Since playground is discontinued i will be closing this issue
