### ISSUE TITLE
`ballerina dist update` fails

### ISSUE THREAD

**Issue by irshadnilam** [ballerina-platform/ballerina-distribution#409]
**Description:**
$title
<img width="745" alt="Screen Shot 2019-12-20 at 10 08 33 AM" src="https://user-images.githubusercontent.com/24229626/71230711-b9179200-2310-11ea-9c82-ff89df85b836.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by keizer619** [comment]
This happened due to failure in the server side, we have fixed that
