### ISSUE TITLE
Java version detection logic results in false positives

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-distribution#410]
**Description:**
For example `ballerina help` works even though the version is incompatible.

Update: The [current check](https://github.com/ballerina-platform/ballerina-distribution/blob/v1.1.0/resources/tools/bin/ballerina#L44) is `-version 2>&1 | grep "1.8."`, however this also matches non-1.8 versions such as a Java 11 version that has `1.118.04` in the output. 

**Affected Product Version:**
1.1.0-rc1

**Comment by Urahara** [comment]
This is already solved? Because you can use: `\.` to match desired result. Example:

```sh
$ java -version 2>&1 | grep "1\.8."
```

Match:
java version "**1.8**.0_201"
Java(TM) SE Runtime Environment (build **1.8.**0_201-b09)

But not: 1.118.04

**Comment by keizer619** [comment]
Currently we do not check Java version as we have compiled it in Java 8 and let support with new java versions. 
However we check existence of specific JREs which have been packed along with ballerina and use that if those available
https://github.com/ballerina-platform/ballerina-update-tool/blob/master/resources/bin/bal#L25
