### ISSUE TITLE
Improvement to Ballerina dist update Command

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-platform/ballerina-distribution#414]
**Description:**
If the latest patch version is available locally we do not need to check remote,

![Screenshot 2019-12-20 at 13 58 03](https://user-images.githubusercontent.com/1329674/71241332-5da9cc00-2331-11ea-959e-bd0676486ed5.png)

**Steps to reproduce:**
v0.8.0 at least

**Comment by keizer619** [comment]
The latest version is handled in server side, so even 1.0.5 latest at given time is available in local, there could 1.0.6 release sometime later. In that case we need to check
