### ISSUE TITLE
Ballerina dist command accepts invalid args in the middle

### ISSUE THREAD

**Issue by rasika** [ballerina-platform/ballerina-distribution#415]
**Description:**
`ballerina dist` command accepts invalid args in the middle.

`ballerina dist foo is the greatest in the list` works fine as same as `ballerina dist list`

This works for the `pull` and `use` as well. 

**Affected Product Version:**
1.1.0

**Comment by AnsarMahir** [comment]
@keizer619 can you assign me on this and guide me a bit on the guidelines

**Comment by Ishad-M-I-M** [comment]
@keizer619 Can I get this assigned to me

**Comment by Ishad-M-I-M** [comment]
@keizer619 Isn't this issue is related to the (ballerina-update-tool)[https://github.com/ballerina-platform/ballerina-update-tool] ?
