### ISSUE TITLE
Getting ballerina 1.0.5 download message after switch into 1.0.3v

### ISSUE THREAD

**Issue by warunalakshitha** [ballerina-platform/ballerina-distribution#423]
**Description:**
I switched to ballerina 1.0.3 using ballerina 1.0.5 installer. when I type ballerina build, still getting following message with 'ballerina build' cmd

A new Ballerina version is available : 1.0.5
You can download the installer of it from https://ballerina.io/downloads/.

**Comment by keizer619** [comment]
Since these not happening in swan lake releases i am closing this, if there are any concerns please feel free to reopen
