### ISSUE TITLE
Come up with a better way to provide the keystore path in BBEs

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-distribution#581]
Currently, in BBEs, when you need to specify the keystore path, it's done by passing a config, `--b7a.home` and concatenating it with the fixed portion of the path to the sample keystore in the distribution. The problem with this is the examples mention to provide the path of the home to `--b7a.home`. e.g., the HTTPS listener example says,
```
$ ballerina run https_listener.bal --b7a.home=<ballerina_home_path>
```

But setting the path of the home doesn't work. You actually need to give the path of the particular distribution you are using. This is misleading because what we usually refer to as the Ballerina home dir is the path where you have installed Ballerina.

**Comment by ldclakmal** [comment]
Yes. As of Swan Lake Beta1, this method of providing keystore/truststore path are no longer there. The keystore/truststore path is given as the absolute/relative path when we configure it from the code. Additionally, we can use the `configurable` feature to configure the path. These are the only 2 options to specify the keystore/truststore path. Hence, closing the issue.
