### ISSUE TITLE
Review newly added `readonly` BBEs

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-distribution#597]
**Description:**
Need to $title.

Relevant PRs:
- https://github.com/ballerina-platform/ballerina-distribution/pull/559
- https://github.com/ballerina-platform/ballerina-distribution/pull/590

**Comment by praneesha** [comment]
Addressed via the newly-revamped BBEs:

- https://ballerina.io/learn/by-example/readonly-type.html
- https://ballerina.io/learn/by-example/readonly-and-isolated.html
