### ISSUE TITLE
Add daily build to the ballerina distribution

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-distribution#714]
**Description:**
We can do the $subject using either
- Github action
- Jenkins job

Enabling daily build make it easy to track how recent language and stdlib changes will affect to the final distribution and BBEs.

**Comment by BuddhiWathsala** [comment]
@keizer619 @ThisaruGuruge WDYT?. Shall we enable a github action as a daily build?

**Comment by ThisaruGuruge** [comment]
> @keizer619 @ThisaruGuruge WDYT?. Shall we enable a github action as a daily build?

+1
