### ISSUE TITLE
 "Handling Different Payload Types" is not complete

### ISSUE THREAD

**Issue by riyafa** [ballerina-platform/ballerina-distribution#728]
**Description:**
The example "[Handling Different Payload Types](https://ballerina.io/swan-lake/learn/by-example/different-payload-types.html)" is incomplete on the website because of the following reasons:

- Only the details about running the server are provided. Details on running a client to test how the server works is missing

- The server is looking for a file at the location `./files/logo.png`. The details about having to provide such an image when running the example is not given.

**Affected Product Version:**
Swan lake preview

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
The second issue mentioned in the above exists for some other BBEs too. Check and fix them too. Ex: byte-io BBE
