### ISSUE TITLE
BBE - No need to explicitly close DB client query operation result stream 

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#730]
**Description:**

$Subject for BBEs such as Select Query Operations, Query with Complex Types etc. 

If the stream is fully iterated using foreach it will get closed automatically and underlying resources like DB connection etc will get released.  So we don't need to explicitly close the result stream using `close()` function. So in BBEs we need to emphasize this automatic clsong behaviour and only use `close()` function if we not iterating at all or using `next()` function to get the first element only.

So need to check all data client related BBEs and fix this.

**Steps to reproduce:**

I used following sample code to validate this automatic closing behaviour.

```ballerina
import ballerina/io;
import ballerina/java.jdbc;
import ballerina/sql;

public function main() {
    jdbc:Client|sql:Error jdbcClient = initializeDatabase();
    if (jdbcClient is jdbc:Client) {
        fetchData(jdbcClient);
        fetchData(jdbcClient);
        fetchData(jdbcClient);
        sql:Error? e = jdbcClient.close();
    }
}

function fetchData(jdbc:Client jdbcClient) {
    stream<record {}, error> resultStream = jdbcClient->query("SELECT * FROM Users");


    //Case 1: Fully iterating the stream. We dont want explicit resultStream.close(); here.
    error? e = resultStream.forEach(function(record {} result) {
        io:println("Data: ", result);
    });
    if(e is error) {
        io:println("ERROR", e);
    }
    // e = resultStream.close();


    // Case 2: Not fully iterating the stream. We need expicit close here as the pool size is 2
    // and fetchData method is invoking 3 times from main.
    // record {|record {} value;|}|error? result = resultStream.next();

    // if (result is record {|record {} value;|}) {
    //     io:println("data : ", result);
    // } else if (result is error) {
    //     io:println("Next operation on the stream failed. ", result);
    // } else {
    //     io:println("Customer table is empty");
    // }
    // error? er = resultStream.close();

}

function initializeDatabase() returns jdbc:Client|sql:Error {
    sql:ConnectionPool connPool = {
        maxOpenConnections: 2
    };
    jdbc:Client|sql:Error jdbcClient = new ("jdbc:h2:file:./target/customers", "rootUser", "rootPass", (), connPool);
    if (jdbcClient is jdbc:Client) {
        sql:ExecutionResult result = check jdbcClient->execute("DROP TABLE IF EXISTS Users");
        //Create table Users and populate sample data
        result = check jdbcClient->execute("CREATE TABLE IF NOT EXISTS Users(username  VARCHAR(300) NOT NULL," +
            "status INTEGER, password  VARCHAR(300), PRIMARY KEY (username))");
        result = check jdbcClient->execute("INSERT INTO Users (username,status,password) VALUES ('Peter', 1, 'pass1')");
        result = check jdbcClient->execute("INSERT INTO Users (username,status,password) VALUES ('Dan', 1, 'pass2')");
        result = check jdbcClient->execute("INSERT INTO Users (username,status,password) VALUES ('Anupama', 0, 'pass2')");
    } else {
        io:println("DB Initialization failed!!");
    }
    return jdbcClient;
}




```

**Affected Versions:**

Swan lake

**Comment by niveathika** [comment]
@anupama-pathirage As per the latest design. Even if forEach is used in the stream, we have to call the close() method. 

@pcnfernando @mohanvive Your thoughts on this. If we can improve streams which will call a method finally for `forEach()` method, it will be more user friendly

**Comment by mohanvive** [comment]
@niveathika We had a few iterations on this. Let's have a chat. @grainier

**Comment by grainier** [comment]
AFAIR, we came to the conclusion that the user has to explicitly call `close()` method. And for the iterator of the resultset, it should implement a `close` method to release underlying resources like DB connection. So if the user wants to stop the stream in the middle of an iteration or release resources after the iteration, they have to explicitly call close.

@niveathika I agree with your point of having finally, but afaik we don't have try-finally in ballerina. So that's why we have to `trap` any exceptions, close the resources and then proceed with the rest.  

@mohanvive will have a chat on this.

**Comment by mohanvive** [comment]
@grainier Now, we have some thing called on-fail clause which is similar to try-catch. Let's schedule a meeting to discuss this.

**Comment by grainier** [comment]
@niveathika, @daneshk As per spec discussion on ballerina-platform/ballerina-spec#592, the idempotent nature of the close function and auto-closing behaviour of stream must be implemented by the Iterator implementer (i.e refer to [1]). So. the underlying Iterator of `resultStream` should be written in a way to adhere to that.

[1] https://github.com/ballerina-platform/ballerina-lang/issues/25450#issuecomment-686293954

**Comment by niveathika** [comment]
@all I have validated the idempotent nature of `ResultIterator` used in SQL modules and updated the BBEs in https://github.com/ballerina-platform/ballerina-distribution/pull/758
