### ISSUE TITLE
Issue's with build on arch linux

### ISSUE THREAD

**Issue by arjunv27** [ballerina-platform/ballerina-distribution#94]
**Description:**
I'm new to maven and java dev environments. 
Arch linux does some weird stuff when it installs  openjdk.
 It maps to a program called archlinux-java and $JAVA_HOME doesn't exist.

**OS, DB, other environment details and versions:**    
Arch linux

**Steps to reproduce:**
pacman -S jdk8-openjdk maven nodejs  npm
git clone --recursive https://github.com/ballerina-platform/ballerina-lang
git submodule update --init 
mvn clean install
When I do it this way the build fails on installing toml

When I download the zip and attempt to run any binary, it gives me a JAVA_HOME error -- which 
I set JAVA_HOME to /usr/lib/jvm/java-8-jdk
and I tried /usr/lib/jvm/java-8/jdk/bin
both recieved ERROR: JAVA_HOME is not defined correctly

**Comment by a5anka** [comment]
@arjunv27 trying with JAVA_HOME set to `/usr/lib/jvm/java-8-openjdk/`.

**Comment by ayomawdb** [comment]
@arjunv27 . Doing a `ls` on the `/usr/lib/jvm` will help in finding out the correct JDK location. You should be able to use `which` to locate the Java home when installed with pcman (`which javac`).  JAVA_HOME should point to the JDK home. Hence you need not add "/bin" at the end.  

Please reopen the issue if you are still experience same problem with the build process after setting the correct JAVA_HOME.
