### ISSUE TITLE
Disabled Tests with project API migration

### ISSUE THREAD

**Issue by keizer619** [ballerina-platform/ballerina-distribution#950]
**Description:**
We have disabled following  tests. We need to enable them

- [x] BBE Output verification 
- [ ] Extension Tests

BBE Tests
- [x] http-retry
- [x] http-failover
- [x] http-load-balancer
- [x] http-circuit-breaker
- [x] http-redirects
- [x] cache
- [x] websocket-proxy-server
- [x] crypto
- [x] math-functions
- [x] java-arrays
- [x] record-io
- [x] modules
- [x] any-type
- [x] secured_client_with_oauth2
- [x] send_and_receive_emails
- [x] task-scheduler-appointment
- [x] secured-client-with-jwt-auth
- [x] secured-client-with-basic-auth
- [x] secured-service-with-jwt-auth
- [x] secured-service-with-basic-auth
- [x] jwt-issue-validate
- [ ] file-io

StdLib Tests
- [x] io
- [x] sql
- [x] kafka
- [x] crypto
- [x] mime
- [x] http

**Comment by keizer619** [comment]
io test is handled in this PR https://github.com/ballerina-platform/ballerina-distribution/pull/945

**Comment by ldclakmal** [comment]
Enabled security BBEs with https://github.com/ballerina-platform/ballerina-distribution/pull/988

**Comment by ldclakmal** [comment]
Enabled crypto stdlib tests with https://github.com/ballerina-platform/ballerina-distribution/pull/991

**Comment by niveathika** [comment]
Enabled rest of the test cases in https://github.com/ballerina-platform/ballerina-distribution/pull/1055/commits/ac868f5f28effedbabc88778448ddef9fb5a2835
